name = "memorysystem"

main = "index.js"

compatibility_date = "2024-01-01"

[[d1_databases]]

binding = "DB"

database_name = "memory-db"

database_id = "94515cf4-4d04-4e01-abed-7cb646a0ce26"

[vars]
ADMIN_EMAIL = "1065857324@qq.com"
INVITE_CODE = "cong1997"
JWT_SECRET = "memory-system-jwt-secret-2026"
FEISHU_HOOK = "https://open.feishu.cn/open-apis/bot/v2/hook/5741cf98-9a86-4754-a5bd-8109a2cacca4"
